// Compiles guide/*.md into src/guide-sources.generated.ts (spec 04 "Platform guide").
// Run after editing the guide: pnpm -F @repo/app-contract build:guide
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const TOPIC_ORDER = [
  'workflow',
  'contract',
  'database',
  'storage',
  'email',
  'secrets',
  'limits',
  'troubleshooting',
];

const root = fileURLToPath(new URL('..', import.meta.url));
export const OUTPUT = `${root}src/guide-sources.generated.ts`;

export function generateGuideModule() {
  const entries = TOPIC_ORDER.map((topic) => {
    const markdown = readFileSync(`${root}guide/${topic}.md`, 'utf8');
    return `  ${topic}: ${JSON.stringify(markdown)},`;
  });
  return `// Generated by scripts/build-guide.mjs from guide/*.md — do not edit by hand.\nexport const GUIDE_SOURCES = {\n${entries.join('\n')}\n} as const;\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUTPUT, generateGuideModule());
  process.stdout.write(`wrote ${OUTPUT}\n`);
}
